### ISSUE TITLE
Project build failing after upgrade to 1.2.0

### ISSUE THREAD

**Issue by byrnedo** [thefrontside/emberx-file-input#58]
Hi, 
We just upgraded from 1.1.2 to 1.2.0 and now we get the following: 
`Build failed.
The Broccoli Plugin: [broccoli-persistent-filter:CleanCSSFilter] failed with:
Error: ENOENT: no such file or directory, open '/home/donal/dev/app/tmp/source_map_concat-input_base_path-VbHnNMO6.tmp/vendor/style.css'`

I rolled back and everything works fine.

ember-cli: 2.15.1
node: 6.12.0
os: linux x64

Full stack trace:

```
Build failed.
The Broccoli Plugin: [broccoli-persistent-filter:CleanCSSFilter] failed with:
Error: ENOENT: no such file or directory, open '/home/donal/dev/app/tmp/source_map_concat-input_base_path-VbHnNMO6.tmp/vendor/style.css'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at SourceMap.addFile (/home/donal/dev/app/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /home/donal/dev/app/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/home/donal/dev/app/node_modules/broccoli-concat/concat.js:198:24)
    at /home/donal/dev/app/node_modules/fast-sourcemap-concat/lib/source-map.js:419:12
    at initializePromise (/home/donal/dev/app/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/home/donal/dev/app/node_modules/rsvp/dist/rsvp.js:1039:33)
    at SourceMap.end (/home/donal/dev/app/node_modules/fast-sourcemap-concat/lib/source-map.js:406:10)
    at Concat._doLegacyBuild (/home/donal/dev/app/node_modules/broccoli-concat/concat.js:183:22)
    at Concat.build (/home/donal/dev/app/node_modules/broccoli-concat/concat.js:106:17)
    at /home/donal/dev/app/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/home/donal/dev/app/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/donal/dev/app/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/donal/dev/app/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/donal/dev/app/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at: 
    at CleanCSSFilter.Plugin (/home/donal/dev/app/node_modules/broccoli-plugin/index.js:7:31)
    at CleanCSSFilter.Filter [as constructor] (/home/donal/dev/app/node_modules/broccoli-persistent-filter/index.js:64:10)
    at new CleanCSSFilter (/home/donal/dev/app/node_modules/broccoli-clean-css/index.js:17:10)
    at CleanCSSFilter (/home/donal/dev/app/node_modules/broccoli-clean-css/index.js:12:12)
    at module.exports.preprocessMinifyCss (/home/donal/dev/app/node_modules/ember-cli-preprocess-registry/preprocessors.js:112:12)
    at EmberApp.styles (/home/donal/dev/app/node_modules/ember-cli/lib/broccoli/ember-app.js:1377:24)
    at EmberApp.toArray (/home/donal/dev/app/node_modules/ember-cli/lib/broccoli/ember-app.js:1690:12)
    at EmberApp.toTree (/home/donal/dev/app/node_modules/ember-cli/lib/broccoli/ember-app.js:1711:38)
    at module.exports (/home/donal/dev/app/ember-cli-build.js:51:14)
    at Builder.setupBroccoliBuilder (/home/donal/dev/app/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/donal/dev/app/node_modules/ember-cli/lib/models/builder.js:30:10)
    at BuildTask.run (/home/donal/dev/app/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/home/donal/dev/app/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatch (/home/donal/dev/app/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/donal/dev/app/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/donal/dev/app/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/donal/dev/app/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)


```

**Comment by kevinansfield** [comment]
@byrnedo I think the underlying cause is the same as https://github.com/thefrontside/emberx-file-input/issues/57 - the `vendor` dir is missing in the npm package.

**Comment by byrnedo** [comment]
I'll close as duplicate!
